#NAME: Yining Wang
#EMAIL: wangyining@g.ucla.edu
#ID: 504983099

.SILENT:

default:
	gcc -o  lab1a -g -Wall -Wextra lab1a.c

dist: default
	tar -cvzf lab1a-504983099.tar.gz lab1a.c README Makefile 

clean:
	rm lab1a lab1a-504983099.tar.gz